export const url = {
  home: "/",
  aboutus: "/Aboutus",
  NewArrivals: "arrivals",
  fashion: "/Fashion",
  lakmeone:"/Lakmeone",
  lakmetwo:"/Lakmetwo",
  lakmethree:"/Lakmethree",
  lakmefour:"/Lakmefour",
  lakmefive:"/Lakmefive",
  lakmesix:"/Lakmesix",
  SpecialOffers: "offers",
  Meetthedesigner: "meet",
  Contact:"contact",
  Blogs: "blog",
  residential: "/Residential",
  awards: "/Awards",
  colletion: "/Colletion",
  shop: "/Shop",
  events: "/Events",
  collectionwomen: "/Collectionwomen",
  collectionmen: "/Collectionmen",
};
